/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package au.com.rainmore.spark.app

import au.com.rainmore.spark.utilities.StringUtils

import org.apache.commons.text.WordUtils

object App {
   def main(args: Array[String]): Unit = {
        val tokens = StringUtils.split(MessageUtils.getMessage())
        val result = StringUtils.join(tokens)
        println(WordUtils.capitalize(result))
    }
}
